/**
 * Created by adaml on 2/14/2018.
 */
public enum Error {
    LEXER, ILL_FORMED_LABEL, INVALID_OPCODE, TOO_MANY_OPERANDS, TOO_FEW_OPERANDS,ILL_FORMED_OPERANDS, WRONG_OPERAND_TYPE, LABEL_PROBLEMS
}
